### ISSUE TITLE
ERROR! 'isc.rest' not found in any repository.

### ISSUE THREAD

**Issue by mwaseem75** [intersystems/isc-rest#12]
Hi,
zpm install raising below error
 
 "ERROR! 'isc.rest' not found in any repository"

**Comment by isc-tleavitt** [comment]
@mwaseem75 can you provide the output of:
zpm "list"
zpm "repo -list"
zpm "repo -list-modules"

**Comment by isc-tleavitt** [comment]
Closing as this issue is stale. Likely cause is use of a different registry; it's possible to switch back with e.g.
```
zpm "repo -n registry -r -url https://pm.community.intersystems.com"
```

see for reference: https://community.intersystems.com/post/testing-packages-zpm
